version: "3.9"

networks:
  dev-network:
    driver: bridge

services:
  database:
    build: 
      context: db
      dockerfile: ./Dockerfile
    image: comment_system_database
    container_name: lb_3_db
    ports:
      - "5400:5432"
    restart: always
    networks:
      - dev-network

  backend:
    build:
      context: backend
      dockerfile: ./Dockerfile
    image: comment_system_backend
    container_name: lb_3_backend
    ports:
      - "8080:8080"
    restart: always
    networks:
      - dev-network
    depends_on:
      - database

  fronted:
    build:
      context: frontend
      dockerfile: ./Dockerfile
    image: comment_system_frontend
    container_name: lb_3_frontend
    ports:
      - "3000:3000"
    restart: always
    networks:
      - dev-network
    depends_on:
      - backend
